# vars this task expects
#        pvc_namespace: "{{ item.pvc_namespace }}"
#        pvc_name: "{{ item.pvc_name }}"
#        pod_name: "{{ pvc_name }}-ssh-rync"
#        svc_name: "{{ pvc_namespace }}-ssh"
#        volume_name: "{{ item.volume_name }}"
#        secret_name: "{{ pod_name }}-public-key"
#        bound_pod_uid: "{{ item.bound_pod_uid }}"
#        mig_source_host: "{{ item.node_name }}"

- debug:
    msg: "{{ item }}"

################### Experimental #############################
# TODO: inject dynamic public key
# try with poststart hook to get right permissions
#       lifecycle:
#          postStart:
#            exec:
#              command:
#                - /bin/sh
#                - -c
#                - cp /var/my-app-secrets/id_rsa /var/my-app/id_rsa
#- name: create a secret for public key
#  k8s:
#    state: present
#    definition:
#      api_version: v1
#      kind: Secret
#      metadata:
#        name: "{{ secret_name }}"
#        namespace: "{{ pvc_namespace }}"
#      data:
#        authorized_keys: "{{ public_key }}"
###########################################################################

- set_fact:
    transfer_pod_wait_retries: 200
    transfer_svc_wait_retries: 200 

- debug:
    msg: "{{ lookup('template', 'pod.yml.j2') }}"

- name: "Create a deployment for rsync"
  k8s:
    state: present
    definition: "{{ lookup('template', 'deploy.yml.j2') }}"

- name: "Create a service for rsync"
  k8s:
    state: present
    definition: "{{ lookup('template', 'svc.yml.j2') }}"

- name: "Wait for pod to be running"
  k8s_info:
    api_version: v1
    kind: pod
    namespace: "{{ pvc_namespace }}"
    label_selectors:
      - "app={{ pod_name }}"
  register: pod
  until: "true in (pod | json_query('resources[].status.containerStatuses[].ready'))"
  retries: "{{ transfer_pod_wait_retries }}"
  delay: 3

- name: "Wait for svc to get a load balancer IP"
  k8s_facts:
    api_version: v1
    kind: service
    name: "{{ svc_name }}"
    namespace: "{{ pvc_namespace }}"
  register: svc
  until: " svc.resources is defined
            and svc.resources[0].status is defined
            and svc.resources[0].status.loadBalancer is defined
            and svc.resources[0].status.loadBalancer.ingress is defined"
  retries: "{{ transfer_svc_wait_retries }}"
  delay: 3

- set_fact:
    failed_pvcs: []
    successful_pvcs: []

- name: "Run rsync for pvc synchronously"
  vars:
    pvc_ns: "{{ item.pvc_namespace }}"
    pvc_name: "{{ item.pvc_name }}"
    volume_name: "{{ item.pvc_name }}"
    bound_pod_uid: "{{ item.bound_pod_uid }}"
    node_name: "{{ item.node_name }}"
  include_tasks: "tasks/rsync.yml"
  with_items: "{{ pvcs }}"

- name: "Cleanup the deployment for rsync"
  k8s:
    state: absent
    definition: "{{ lookup('template', 'deploy.yml.j2') }}"

- name: "Wait for pod to be deleted"
  k8s_info:
    api_version: v1
    kind: pod
    namespace: "{{ pvc_namespace }}"
    label_selectors:
      - "app={{ pod_name }}"
  register: p
  until: "{{ p.resources | length == 0 }}"
  retries: 100
  delay: 3

- name: "Cleanup the service for rsync"
  k8s:
    state: absent
    definition: "{{ lookup('template', 'svc.yml.j2') }}"

- name: "Wait for service to be deleted"
  k8s_info:
    api_version: v1
    kind: service
    name: "{{ svc_name }}"
    namespace: "{{ pvc_namespace }}"
  register: s
  until: "{{ s.resources | length == 0 }}"
  retries: 100
  delay: 3

- name: "Printing failed / succeded pvcs"
  debug: 
    msg: "{{ failed_pvcs }} {{ successful_pvcs }}"

- name: "Dumping failure report"
  copy:
    content: "{{ failed_pvcs | to_json }}"
    dest: "{{ failed_pvcs_dir }}/{{ pvc_namespace }}-failed.json"

- name: "Dumping success report"
  copy:
    content: "{{ successful_pvcs | to_json }}"
    dest: "{{ successful_pvcs_dir }}/{{ pvc_namespace }}-successful.json"
